title: Zhao JingWei's Homepage
page-top-title: Zhao JingWei
top-section-bg-text: Le vent se lève, il faut tenter de vivre
home-subtitle: Zhao JingWei&ensp;|&ensp;赵境伟
copyright-text: '&copy; Zhao JingWei 2020-2025. All Rights Reserved.'
